### ISSUE TITLE
Sauce Labs/Travis integration broken

### ISSUE THREAD

**Issue by spamguy** [spamguy/diplomacy#1]
Protractor tests fail when running on Travis/Sauce Labs. The express server is running but SL claims it isn't. Probably missing some obvious step.

```
[4mRunning "express:dev" (express) task[24m
[36mStarting [39mbackground Express server
Express server listening on 9000

[4mRunning "protractor:e2e" (protractor) task[24m
[launcher] Running 1 instances of WebDriver
.
------------------------------------
[chrome #1] PID: 3611
[chrome #1] Specs: /home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js
[chrome #1] 
[chrome #1] Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[chrome #1] [31mF[0m
[chrome #1] 
[chrome #1] Failures:
[chrome #1] 
[chrome #1]   1) Home page should pass
[chrome #1]    Message:
[chrome #1]      [31mError: Angular could not be found on the page http://localhost:9000/ : retries looking for angular exceeded[0m
[chrome #1]    Stacktrace:
[chrome #1]      Error: Angular could not be found on the page http://localhost:9000/ : retries looking for angular exceeded
[chrome #1] ==== async task ====
[chrome #1] Protractor.get(http://localhost:9000/) - test for angular
[chrome #1]     at [object Object].<anonymous> (/home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js:7:13)
[chrome #1] ==== async task ====
[chrome #1] Asynchronous test function: beforeEach()
[chrome #1] Error
[chrome #1]     at [object Object].<anonymous> (/home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js:6:3)
[chrome #1]     at Object.<anonymous> (/home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js:3:1)
[chrome #1] 
[chrome #1] Finished in 11.753 seconds
[chrome #1] [31m1 test, 2 assertions, 1 failure
[0m[chrome #1] 
[chrome #1] SauceLabs results available at http://saucelabs.com/jobs/18be5a61fde8436ba112f497829793b5

[launcher] 1 instance(s) of WebDriver still running
.
------------------------------------
[firefox #2] PID: 3620
[firefox #2] Specs: /home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js
[firefox #2] 
[firefox #2] Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[firefox #2] [31mF[0m
[firefox #2] 
[firefox #2] Failures:
[firefox #2] 
[firefox #2]   1) Home page should pass
[firefox #2]    Message:
[firefox #2]      [31mError: Angular could not be found on the page http://localhost:9000/ : retries looking for angular exceeded[0m
[firefox #2]    Stacktrace:
[firefox #2]      Error: Angular could not be found on the page http://localhost:9000/ : retries looking for angular exceeded
[firefox #2] ==== async task ====
[firefox #2] Protractor.get(http://localhost:9000/) - test for angular
[firefox #2]     at [object Object].<anonymous> (/home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js:7:13)
[firefox #2] ==== async task ====
[firefox #2] Asynchronous test function: beforeEach()
[firefox #2] Error
[firefox #2]     at [object Object].<anonymous> (/home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js:6:3)
[firefox #2]     at Object.<anonymous> (/home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js:3:1)
[firefox #2] 
[firefox #2] Finished in 12.395 seconds
[firefox #2] [31m1 test, 2 assertions, 1 failure
[0m[firefox #2] 
[firefox #2] SauceLabs results available at http://saucelabs.com/jobs/f377fddad0c54483b2e5ec2a5afc18cd

[launcher] 1 instance(s) of WebDriver still running

------------------------------------
[ #3] PID: 3637
[ #3] Specs: /home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js
[ #3] 
[ #3] Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[ #3] Target browser must be a string, but is <object>; did you forget to call forBrowser()?

[launcher] Runner process exited unexpectedly with error code: 1
[launcher] 1 instance(s) of WebDriver still running

------------------------------------
[ #4] PID: 3642
[ #4] Specs: /home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js
[ #4] 
[ #4] Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[ #4] Target browser must be a string, but is <object>; did you forget to call forBrowser()?

[launcher] Runner process exited unexpectedly with error code: 1
[launcher] 1 instance(s) of WebDriver still running

------------------------------------
[ #5] PID: 3647
[ #5] Specs: /home/travis/build/spamguy/diplomacy/e2e/main/main.spec.js
[ #5] 
[ #5] Using SauceLabs selenium server at http://ondemand.saucelabs.com:80/wd/hub
[ #5] Target browser must be a string, but is <object>; did you forget to call forBrowser()?

[launcher] Runner process exited unexpectedly with error code: 1
[launcher] 0 instance(s) of WebDriver still running
[launcher] chrome #1 failed 1 test(s)
[launcher] firefox #2 failed 1 test(s)
[launcher]  #3 failed with exit code: 1
[launcher]  #4 failed with exit code: 1
[launcher]  #5 failed with exit code: 1
[launcher] overall: 2 failed spec(s) and 3 process(es) failed to complete
[launcher] Process exited with error code 100
[31m>> [39m
[31mFatal error: protractor exited with code: 100[39m
[37m[40mnpm[0m [0m[31m[40mERR![0m[35m[0m Test failed.  See above for more details.
[0mtravis_time:end:042f976b:start=1426050337513705673,finish=1426050384808086135,duration=47294380462
[0K
[31;1mThe command "npm test" exited with 1.[0m
travis_fold:start:sauce_connect.stop
[0K[33;1mStopping Sauce Connect[0m
travis_time:start:16074c13
[0K$ travis_stop_sauce_connect
Waiting for graceful Sauce Connect shutdown
11 Mar 05:06:24 - Cleaning up.
11 Mar 05:06:25 - Shutting down named tunnel 46.1 (d2dc81704e6b4ec19f483ce74511dc54).
Waiting for graceful Sauce Connect shutdown
Waiting for graceful Sauce Connect shutdown
Waiting for graceful Sauce Connect shutdown
Waiting for graceful Sauce Connect shutdown
11 Mar 05:06:29 - Goodbye.
Sauce Connect shutdown complete
travis_time:end:16074c13:start=1426050384816562203,finish=1426050389833749012,duration=5017186809
[0Ktravis_fold:end:sauce_connect.stop
```

**Comment by spamguy** [comment]
Fixed on newgame branch.
